domain_path: /home/user16/workspace_soc/platform_stepper/export/platform_stepper/sw/standalone_microblaze_riscv_0
app_src_dir: /home/user16/Tools/Vitis/2024.2/data/embeddedsw/lib/sw_apps/hello_world
template: hello_world
lang: c
